name: Branch Protection
target: branch
bypass_actors:
  organization_admin: maintain
  repository_admin: maintain
conditions:
  ref_name:
    include:
      - refs/heads/master
      - refs/heads/main
rules:
  - type: pull_request
    parameters:
      dismiss_stale_reviews_on_push: true
      required_approving_review_count: 1
  - type: required_linear_history
    parameters: {}
  - type: non_fast_forward
    parameters: {}
