name: kentnabiz_mobile
description: KentNabız - Şehir Sorunları İzleme ve Müdahale Platformu
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Flutter 3.19 ve sonrası için sdk versiyonunu güncelleyelim

dependencies:
  flutter:
    sdk: flutter

  # Core & UI
  cupertino_icons: ^1.0.6

  # State Management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^13.2.0

  # Networking
  dio: ^5.4.3+1

  # Secure Storage
  flutter_secure_storage: ^9.0.0

  # Logging
  logger: ^2.2.0

  # Environment
  flutter_dotenv: ^5.1.0

  # Code Generation - Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1

  # Code Generation - Runners
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
