name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  basic-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Simple check
        run: |
          echo "Repository successfully cloned"
          ls -la
          node --version

      - name: Success
        run: echo "Basic test completed successfully!"
